version: "3.7"

services:
  # image project
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  mysql:
      image: mysql:latest
      container_name: mysql
      volumes:
          - ./docker/mysql:/var/lib/minesql
      command: --authentication_policy=mysql_native_password
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_db
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
      ports:
          - 3306:3306
      networks:
          - laravel
networks:
    laravel:
      driver: bridge
